# Generated by Django 3.2.4 on 2021-06-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='social.article'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
        migrations.AlterField(
            model_name='likearticle',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1623656538.075457),
        ),
    ]
