# Generated by Django 3.2.4 on 2021-06-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210614_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='social.article'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
        migrations.AlterField(
            model_name='likearticle',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1624515565.832255),
        ),
    ]
