# Generated by Django 3.2.4 on 2021-06-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210608_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1623126537.4773738),
        ),
    ]
