# Generated by Django 3.2.4 on 2021-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210608_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1623136076.6045408),
        ),
    ]
