# Generated by Django 3.2.4 on 2021-06-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210609_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1623299011.010462),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1623299011.010462),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1623299011.010462),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.TextField(default=1623299011.010462),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1623299011.010462),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
