# Generated by Django 3.2.4 on 2021-06-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210610_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='social.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
        migrations.AlterField(
            model_name='likearticle',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like', to='social.comment'),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='create_at',
            field=models.TextField(default=1623321432.99689),
        ),
    ]
